<?php

/**
 * ScanStatus.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
/**
 * Astra v2.
 *
 * APIs for Astra Security Suite
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace AstraPrefixed\GetAstra\Client\Tclient\Model;

/**
 * ScanStatus Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class ScanStatus
{
    /**
     * Possible values of this enum.
     */
    const REQUESTED = 'requested';
    const FAILED = 'failed';
    const STARTED = 'started';
    const RUNNING = 'running';
    const COMPLETED = 'completed';
    const KILLED = 'killed';
    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [self::REQUESTED, self::FAILED, self::STARTED, self::RUNNING, self::COMPLETED, self::KILLED];
    }
}
