<?php

/**
 * SiteCms.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
/**
 * Astra v2.
 *
 * APIs for Astra Security Suite
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace AstraPrefixed\GetAstra\Client\Tclient\Model;

/**
 * SiteCms Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class SiteCms
{
    /**
     * Possible values of this enum.
     */
    const WORDPRESS = 'wordpress';
    const MAGENTO1 = 'magento1';
    const MAGENTO2 = 'magento2';
    const DRUPAL7 = 'drupal7';
    const DRUPAL8 = 'drupal8';
    const OPENCART1 = 'opencart1';
    const OPENCART2 = 'opencart2';
    const OPENCART3 = 'opencart3';
    const JOOMLA = 'joomla';
    const PHP = 'php';
    const MOODLE = 'moodle';
    const PRESTASHOP1_5 = 'prestashop1.5';
    const PRESTASHOP1_6 = 'prestashop1.6';
    const PRESTASHOP1_7 = 'prestashop1.7';
    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [self::WORDPRESS, self::MAGENTO1, self::MAGENTO2, self::DRUPAL7, self::DRUPAL8, self::OPENCART1, self::OPENCART2, self::OPENCART3, self::JOOMLA, self::PHP, self::MOODLE, self::PRESTASHOP1_5, self::PRESTASHOP1_6, self::PRESTASHOP1_7];
    }
}
