<?php

/**
 * SiteWafSiteInput.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
/**
 * Astra v2.
 *
 * APIs for Astra Security Suite
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace AstraPrefixed\GetAstra\Client\Tclient\Model;

use ArrayAccess;
use AstraPrefixed\GetAstra\Client\Tclient\ObjectSerializer;
/**
 * SiteWafSiteInput Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class SiteWafSiteInput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Site-waf_site:input';
    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = ['url' => 'string', 'domain' => 'string', 'name' => 'string', 'connected' => 'bool', 'disconnected_message' => 'string', 'worker_version' => 'string', 'php_version' => 'string', 'type' => 'string', 'version' => 'string', 'locale' => 'string', 'favorite' => 'bool', 'paused' => 'bool', 'last_synced_at' => '\\DateTime', 'api_url' => 'string', 'client_api_token' => 'string', 'disable_pretty_urls' => 'bool', 'plugins' => 'string[]', 'credentials' => 'string'];
    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPIFormats = ['url' => null, 'domain' => null, 'name' => null, 'connected' => null, 'disconnected_message' => null, 'worker_version' => null, 'php_version' => null, 'type' => null, 'version' => null, 'locale' => null, 'favorite' => null, 'paused' => null, 'last_synced_at' => 'date-time', 'api_url' => null, 'client_api_token' => null, 'disable_pretty_urls' => null, 'plugins' => 'iri-reference', 'credentials' => 'iri-reference'];
    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }
    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = ['url' => 'url', 'domain' => 'domain', 'name' => 'name', 'connected' => 'connected', 'disconnected_message' => 'disconnectedMessage', 'worker_version' => 'workerVersion', 'php_version' => 'phpVersion', 'type' => 'type', 'version' => 'version', 'locale' => 'locale', 'favorite' => 'favorite', 'paused' => 'paused', 'last_synced_at' => 'lastSyncedAt', 'api_url' => 'apiUrl', 'client_api_token' => 'clientApiToken', 'disable_pretty_urls' => 'disablePrettyUrls', 'plugins' => 'plugins', 'credentials' => 'credentials'];
    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = ['url' => 'setUrl', 'domain' => 'setDomain', 'name' => 'setName', 'connected' => 'setConnected', 'disconnected_message' => 'setDisconnectedMessage', 'worker_version' => 'setWorkerVersion', 'php_version' => 'setPhpVersion', 'type' => 'setType', 'version' => 'setVersion', 'locale' => 'setLocale', 'favorite' => 'setFavorite', 'paused' => 'setPaused', 'last_synced_at' => 'setLastSyncedAt', 'api_url' => 'setApiUrl', 'client_api_token' => 'setClientApiToken', 'disable_pretty_urls' => 'setDisablePrettyUrls', 'plugins' => 'setPlugins', 'credentials' => 'setCredentials'];
    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = ['url' => 'getUrl', 'domain' => 'getDomain', 'name' => 'getName', 'connected' => 'getConnected', 'disconnected_message' => 'getDisconnectedMessage', 'worker_version' => 'getWorkerVersion', 'php_version' => 'getPhpVersion', 'type' => 'getType', 'version' => 'getVersion', 'locale' => 'getLocale', 'favorite' => 'getFavorite', 'paused' => 'getPaused', 'last_synced_at' => 'getLastSyncedAt', 'api_url' => 'getApiUrl', 'client_api_token' => 'getClientApiToken', 'disable_pretty_urls' => 'getDisablePrettyUrls', 'plugins' => 'getPlugins', 'credentials' => 'getCredentials'];
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }
    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }
    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }
    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }
    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];
    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['domain'] = isset($data['domain']) ? $data['domain'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['connected'] = isset($data['connected']) ? $data['connected'] : null;
        $this->container['disconnected_message'] = isset($data['disconnected_message']) ? $data['disconnected_message'] : null;
        $this->container['worker_version'] = isset($data['worker_version']) ? $data['worker_version'] : null;
        $this->container['php_version'] = isset($data['php_version']) ? $data['php_version'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['locale'] = isset($data['locale']) ? $data['locale'] : null;
        $this->container['favorite'] = isset($data['favorite']) ? $data['favorite'] : null;
        $this->container['paused'] = isset($data['paused']) ? $data['paused'] : null;
        $this->container['last_synced_at'] = isset($data['last_synced_at']) ? $data['last_synced_at'] : null;
        $this->container['api_url'] = isset($data['api_url']) ? $data['api_url'] : null;
        $this->container['client_api_token'] = isset($data['client_api_token']) ? $data['client_api_token'] : null;
        $this->container['disable_pretty_urls'] = isset($data['disable_pretty_urls']) ? $data['disable_pretty_urls'] : null;
        $this->container['plugins'] = isset($data['plugins']) ? $data['plugins'] : null;
        $this->container['credentials'] = isset($data['credentials']) ? $data['credentials'] : null;
    }
    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];
        return $invalidProperties;
    }
    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === \count($this->listInvalidProperties());
    }
    /**
     * Gets url.
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }
    /**
     * Sets url.
     *
     * @param string|null $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;
        return $this;
    }
    /**
     * Gets domain.
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }
    /**
     * Sets domain.
     *
     * @param string|null $domain domain
     *
     * @return $this
     */
    public function setDomain($domain)
    {
        $this->container['domain'] = $domain;
        return $this;
    }
    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }
    /**
     * Sets name.
     *
     * @param string|null $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;
        return $this;
    }
    /**
     * Gets connected.
     *
     * @return bool|null
     */
    public function getConnected()
    {
        return $this->container['connected'];
    }
    /**
     * Sets connected.
     *
     * @param bool|null $connected connected
     *
     * @return $this
     */
    public function setConnected($connected)
    {
        $this->container['connected'] = $connected;
        return $this;
    }
    /**
     * Gets disconnected_message.
     *
     * @return string|null
     */
    public function getDisconnectedMessage()
    {
        return $this->container['disconnected_message'];
    }
    /**
     * Sets disconnected_message.
     *
     * @param string|null $disconnected_message disconnected_message
     *
     * @return $this
     */
    public function setDisconnectedMessage($disconnected_message)
    {
        $this->container['disconnected_message'] = $disconnected_message;
        return $this;
    }
    /**
     * Gets worker_version.
     *
     * @return string|null
     */
    public function getWorkerVersion()
    {
        return $this->container['worker_version'];
    }
    /**
     * Sets worker_version.
     *
     * @param string|null $worker_version worker_version
     *
     * @return $this
     */
    public function setWorkerVersion($worker_version)
    {
        $this->container['worker_version'] = $worker_version;
        return $this;
    }
    /**
     * Gets php_version.
     *
     * @return string|null
     */
    public function getPhpVersion()
    {
        return $this->container['php_version'];
    }
    /**
     * Sets php_version.
     *
     * @param string|null $php_version php_version
     *
     * @return $this
     */
    public function setPhpVersion($php_version)
    {
        $this->container['php_version'] = $php_version;
        return $this;
    }
    /**
     * Gets type.
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }
    /**
     * Sets type.
     *
     * @param string|null $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;
        return $this;
    }
    /**
     * Gets version.
     *
     * @return string|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }
    /**
     * Sets version.
     *
     * @param string|null $version version
     *
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;
        return $this;
    }
    /**
     * Gets locale.
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }
    /**
     * Sets locale.
     *
     * @param string|null $locale locale
     *
     * @return $this
     */
    public function setLocale($locale)
    {
        $this->container['locale'] = $locale;
        return $this;
    }
    /**
     * Gets favorite.
     *
     * @return bool|null
     */
    public function getFavorite()
    {
        return $this->container['favorite'];
    }
    /**
     * Sets favorite.
     *
     * @param bool|null $favorite favorite
     *
     * @return $this
     */
    public function setFavorite($favorite)
    {
        $this->container['favorite'] = $favorite;
        return $this;
    }
    /**
     * Gets paused.
     *
     * @return bool|null
     */
    public function getPaused()
    {
        return $this->container['paused'];
    }
    /**
     * Sets paused.
     *
     * @param bool|null $paused paused
     *
     * @return $this
     */
    public function setPaused($paused)
    {
        $this->container['paused'] = $paused;
        return $this;
    }
    /**
     * Gets last_synced_at.
     *
     * @return \DateTime|null
     */
    public function getLastSyncedAt()
    {
        return $this->container['last_synced_at'];
    }
    /**
     * Sets last_synced_at.
     *
     * @param \DateTime|null $last_synced_at last_synced_at
     *
     * @return $this
     */
    public function setLastSyncedAt($last_synced_at)
    {
        $this->container['last_synced_at'] = $last_synced_at;
        return $this;
    }
    /**
     * Gets api_url.
     *
     * @return string|null
     */
    public function getApiUrl()
    {
        return $this->container['api_url'];
    }
    /**
     * Sets api_url.
     *
     * @param string|null $api_url api_url
     *
     * @return $this
     */
    public function setApiUrl($api_url)
    {
        $this->container['api_url'] = $api_url;
        return $this;
    }
    /**
     * Gets client_api_token.
     *
     * @return string|null
     */
    public function getClientApiToken()
    {
        return $this->container['client_api_token'];
    }
    /**
     * Sets client_api_token.
     *
     * @param string|null $client_api_token client_api_token
     *
     * @return $this
     */
    public function setClientApiToken($client_api_token)
    {
        $this->container['client_api_token'] = $client_api_token;
        return $this;
    }
    /**
     * Gets disable_pretty_urls.
     *
     * @return bool|null
     */
    public function getDisablePrettyUrls()
    {
        return $this->container['disable_pretty_urls'];
    }
    /**
     * Sets disable_pretty_urls.
     *
     * @param bool|null $disable_pretty_urls disable_pretty_urls
     *
     * @return $this
     */
    public function setDisablePrettyUrls($disable_pretty_urls)
    {
        $this->container['disable_pretty_urls'] = $disable_pretty_urls;
        return $this;
    }
    /**
     * Gets plugins.
     *
     * @return string[]|null
     */
    public function getPlugins()
    {
        return $this->container['plugins'];
    }
    /**
     * Sets plugins.
     *
     * @param string[]|null $plugins plugins
     *
     * @return $this
     */
    public function setPlugins($plugins)
    {
        $this->container['plugins'] = $plugins;
        return $this;
    }
    /**
     * Gets credentials.
     *
     * @return string|null
     */
    public function getCredentials()
    {
        return $this->container['credentials'];
    }
    /**
     * Sets credentials.
     *
     * @param string|null $credentials credentials
     *
     * @return $this
     */
    public function setCredentials($credentials)
    {
        $this->container['credentials'] = $credentials;
        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }
    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }
    /**
     * Sets value based on offset.
     *
     * @param int   $offset Offset
     * @param mixed $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (\is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }
    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this), \JSON_PRETTY_PRINT);
    }
    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
